version: '3'
services:
  jennah-site:
    image: ${DOCKERHUB_NAME}/${IMAGE_NAME}:${IMAGE_VERSION}
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      - postgres-primary-db
    command: ["node", "app.js"]
    container_name: ${IMAGE_NAME}
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - my-app-network
  postgres-primary-db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network

